### PR TITLE
use 20201110T135924 in test

### PR DESCRIPTION
**Pull request by aerickson**
built from https://github.com/bclary/mozilla-bitbar-docker/pull/50 @ 74d0dfa

### CODE REVIEW

**Comment by aerickson** [comment]
from https://mozilla.bitbar.com/#testing/device-session/2200108/2353359/64203003: `11-10 14:05:36.882 Successfully tagged mozilla-image:20201110T135924
`

**Review by bclary — APPROVED** [review]
r+

**Comment by aerickson** [comment]
Test run on s7g (root disabled): https://treeherder.mozilla.org/jobs?repo=try&tier=1%2C2%2C3&revision=a3143e873c3221a33e4a1ac5fb59095f31cb538c&group_state=expanded
- no failures due to changes in this PR

**Comment by aerickson** [comment]
`./mach try fuzzy --artifact --full --query "'android-hw 'amazon-search-wr \!vismet \!shippable \!cold" --no-push` with taskcluster/taskgraph/transforms/tests.py changed to point g5 at test-1 and p2 at test-2: https://treeherder.mozilla.org/#/jobs?repo=try&revision=648a37e668314a4a177dd41bbb0803b07219fc38

**Pull request merged**
